### ISSUE TITLE
Installing tensorflow-text issue

### ISSUE THREAD

**Issue by fauzantaufik** [MartinoMensio/spacy-universal-sentence-encoder#10]
ERROR: Could not find a version that satisfies the requirement tensorflow-text<2.4.0,>=2.3.0 (from spacy-universal-sentence-encoder) (from versions: none)
ERROR: No matching distribution found for tensorflow-text<2.4.0,>=2.3.0 (from spacy-universal-sentence-encoder)

![image](https://user-images.githubusercontent.com/33479894/92456800-98200580-f1ed-11ea-83d4-177195fb41b7.png)

**Comment by MartinoMensio** [comment]
Hi @fauzantaufik ,
Which OS are you using? Is it Windows?

What is the output of `pip install tensorflow-text==2.3.0`? Is it failing too? I know there are some problems for Windows and still tensorflow 2.3 does not include a Windows target for the package tensorflow-text (https://github.com/tensorflow/text/issues/291).

`tensorflow-text` is required to run the multilingual models, as you can see on the TensorFlow Hub examples:

- `xx_use_md`: https://tfhub.dev/google/universal-sentence-encoder-multilingual/3
- `xx_use_lg`: https://tfhub.dev/google/universal-sentence-encoder-multilingual-large/3

They said this library will be made available for windows in the next release (https://github.com/tensorflow/text/issues/291). 

For the English models the library is not required, but it is imported anyways. Which models are you trying to use? English or multilingual?

Cheers,
Martino

**Comment by jcardenas14** [comment]
Hi @MartinoMensio , I'm trying to use spacy-universal-sentence-encoder for English models. I am also working with Windows machine and running into the tensorflow-text error. Any workarounds for this?

Thanks!

**Comment by MartinoMensio** [comment]
Hi @jcardenas14,
I just moved the tensorflow-text dependency to multilingual models only. You should be able to install and use English models on Windows. The new version is v0.3.4 (available on pypi https://pypi.org/project/spacy-universal-sentence-encoder/ and GitHub https://github.com/MartinoMensio/spacy-universal-sentence-encoder/releases/tag/v0.3.4)

Let me know if it works for you! :)

Martino

**Comment by MartinoMensio** [comment]
I am closing the issue supposing it is now solved. Please reopen if it is not.

Martino
