### ISSUE TITLE
Retrain models to latest version of Spacy

### ISSUE THREAD

**Issue by dsarmiento84** [MartinoMensio/spacy-universal-sentence-encoder#11]
Hi,

Im bumbing with this warning:
Model 'xx_use_lg' (0.3.2) requires spaCy v2.1,<2 and is incompatible with the current spaCy version (2.3.2)

Can you please retrain the models for this specific version or handle some guidlines to do it?

Thanks.

**Comment by MartinoMensio** [comment]
Hi @dsarmiento84 ,
Thank you for creating the issue. As I mentioned in other issues (#8 #5) the warning can be ignored.
However, I just uploaded a 0.3.3 version that correctly declares the model compatibility.

Please install the new version and let me know if it solves your problem.

Best,
Martino

**Comment by dsarmiento84** [comment]
Thanks @MartinoMensio the warning is gone now.

Best regards
Diego
