### ISSUE TITLE
Update to latest versions of tensorflow and spacy

### ISSUE THREAD

**Issue by Matthieu-Tinycoaching** [MartinoMensio/spacy-universal-sentence-encoder#12]
Hi,

Would it be possible to update your repository to the latest version of tensorflow (2.4) and spacy (>3.0) ?

Indeed, having a RTX 3090 CUDA >=11 is required which implies tensorflow >= 2.4.

Thanks !

**Comment by MartinoMensio** [comment]
Hi Matthieu,
Thank you for your message! I am already working on a new release for the latest tensorflow and spacy. There are some internal changes I still need to solve but that should be quite straightforward. I will let you know when it is released! :)

Martino

**Comment by MartinoMensio** [comment]
Hi @Matthieu-Tinycoaching ,
I just pushed the latest version 0.4.0 which is compatible with tensorflow 2.4 and spacy 3.
It seems to be working fine in my environments, let me know if it is working for you too!

Martino

**Comment by Matthieu-Tinycoaching** [comment]
Hi @MartinoMensio,

Thanks I will check !
