### ISSUE TITLE
SpaCy versions required for en_use_lg-0.4.3

### ISSUE THREAD

**Issue by michkessler** [MartinoMensio/spacy-universal-sentence-encoder#23]
I have a project that requires `spacy==3.2.1`, and I want to include `en_use_lg-0.4.3` in the project as well. 
The spaCy requirements specified for the large model are `"spacy_version":">=3.0.3,<3.1.0"`, which is incompatible with the requirement I already have (3.2.1). 
I tried changing it locally to `"spacy_version":">=3.0.3,<=3.2.1"`, and installed with no problem, and so I was hoping you could update the versions to support spaCy up to the most recent compatible stable version (at least 3.2.1).

**Comment by MartinoMensio** [comment]
Hey @michkessler !
Thank you for opening this issue. There is no real motivation for the upper bound of the spacy version.
This comes purely from how [spaCy carefully recomputes the version range](https://github.com/explosion/spaCy/blob/master/spacy/language.py#L212). The last release of this library was done with spaCy 3.0.3, so I am just going to update every dependency and release a new version.

Best,
Martino

Best,
Martino

**Comment by MartinoMensio** [comment]
In the latest version I override the `spacy_version` that was being modified by the command `spacy package`
